In [ ]:
## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s.split(" ")

['Hi', 'there', 'Sam!']

In [ ]:
## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of Earth is {} kilometers.".format(diameter))

The diameter of Earth is 12742 kilometers.


In [ ]:
## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d1=d['k1'][3]['tricky'][3]['target'][3]
print(d1)

hello


In [ ]:
# Numpy

In [7]:
import numpy as np

In [ ]:
## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
array=np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
array1=np.ones(10)*5
print(array1)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## 5. Create an array of all the even integers from 20 to 35

In [10]:
array2=np.arange(20,35,2)
print(array2)

[20 22 24 26 28 30 32 34]


In [ ]:
## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
n1=np.array([1,2,3])
n2=np.array([4,5,6])
np.concatenate((n1,n2),axis=0)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Pandas

In [ ]:
## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data = {'Name': ['Tom', 'nick', 'krish'],
        'Age': [20, 21, 19]}
  

df = pd.DataFrame(data)
  

df

Name  Age
0    Tom   20
1   nick   21
2  krish   19

In [ ]:
## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
dRan3 = pd.date_range(start ='2023-01-01', end ='2023-02-10').to_pydatetime().tolist()
print(dRan3)

[datetime.datetime(2023, 1, 1, 0, 0), datetime.datetime(2023, 1, 2, 0, 0), datetime.datetime(2023, 1, 3, 0, 0), datetime.datetime(2023, 1, 4, 0, 0), datetime.datetime(2023, 1, 5, 0, 0), datetime.datetime(2023, 1, 6, 0, 0), datetime.datetime(2023, 1, 7, 0, 0), datetime.datetime(2023, 1, 8, 0, 0), datetime.datetime(2023, 1, 9, 0, 0), datetime.datetime(2023, 1, 10, 0, 0), datetime.datetime(2023, 1, 11, 0, 0), datetime.datetime(2023, 1, 12, 0, 0), datetime.datetime(2023, 1, 13, 0, 0), datetime.datetime(2023, 1, 14, 0, 0), datetime.datetime(2023, 1, 15, 0, 0), datetime.datetime(2023, 1, 16, 0, 0), datetime.datetime(2023, 1, 17, 0, 0), datetime.datetime(2023, 1, 18, 0, 0), datetime.datetime(2023, 1, 19, 0, 0), datetime.datetime(2023, 1, 20, 0, 0), datetime.datetime(2023, 1, 21, 0, 0), datetime.datetime(2023, 1, 22, 0, 0), datetime.datetime(2023, 1, 23, 0, 0), datetime.datetime(2023, 1, 24, 0, 0), datetime.datetime(2023, 1, 25, 0, 0), datetime.datetime(2023, 1, 26, 0, 0), datetime.datetime(20

In [ ]:
## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
df = pd.DataFrame(lists, columns =['ID', 'number','no']) 
print(df)

   ID number  no
0   1    aaa  22
1   2    bbb  25
2   3    ccc  24
